name: Build aarch64

on: [push]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://dia:dia@postgres:5432/dia

jobs:
  linux_aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dia
          POSTGRES_USER: dia
          POSTGRES_DB: dia

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release
      - uses: actions/upload-artifact@v2
        with:
          name: dia-aarch64
          path: target/aarch64-unknown-linux-musl/release/dia
