name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgresql://dia:dia@postgres:5432/dia

jobs:
    build:
        runs-on: ubuntu-latest
        container: rust

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: dia
                    POSTGRES_USER: dia
                    POSTGRES_DB: dia
            redis:
                image: redis

        steps:
            - uses: actions/checkout@v2
            - name: Setup CI config
              run: mv ci-config.toml config.toml
            - name: Build
              run: cargo build --verbose --release
