name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://dia:dia@postgres:5432/dia

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rust

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dia
          POSTGRES_USER: dia
          POSTGRES_DB: dia
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v2
      - name: Setup CI config
        run: mv ci-config.toml config.toml
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Run Postgres migrations
        run: sqlx migrate run
      - name: Run tests
        run: cargo test --verbose
  test:
    name: Test
    runs-on: ubuntu-latest
    container: rust

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dia
          POSTGRES_USER: dia
          POSTGRES_DB: dia
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v2
      - name: Setup CI config
        run: mv ci-config.toml config.toml
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Run Postgres migrations
        run: sqlx migrate run
      - name: Run tests
        run: cargo test --verbose
  build_aarch64:
    name: Build aarch64
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dia
          POSTGRES_USER: dia
          POSTGRES_DB: dia

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release
      - uses: actions/upload-artifact@v2
        with:
          name: dia-aarch64
          path: target/aarch64-unknown-linux-musl/release/dia
